### ISSUE TITLE
Camera Parameters

### ISSUE THREAD

**Issue by 1174466421** [HAWKEYE-Group/UrbanLF#1]
Hello, I would like to ask you about the detailed parameters of the UrbanLF-syn dataset camera (e.g. focal length, distance between adjacent viewpoints, probe size, etc.)

**Comment by HAWKEYE-Group** [comment]
We have updated camera parameters of UrbanLF-Syn

**Comment by DerBrecher** [comment]
@HAWKEYE-Group I noticed that the provided camera parameters are only listed for 250 Images for both UrbanLF-Syn-Big and UrbanLF-Syn-Small. Am I correct in assuming that these correspond to the 250 images contained in the original UrbanLF-Syn? Is there any way to obtain the parameters for the remaining 150 Images?
